services:
  - type: web
    name: frutiger-messenger
    env: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: frutiger-db
          attribute: connectionString

databases:
  - name: frutiger-db
    plan: free